const fs = require('fs');
const path = require('path');
const { AGENTS_MD_PATH, collectSkillDirectories, extractYamlField, stripFrontmatter, readMeaningfulMarkdown } = require('../shared.js');

// Aider config goes to project root
const CONF_FILE        = path.join(process.cwd(), '.aider.conf.yml');
const CONVENTIONS_FILE = path.join(process.cwd(), 'CONVENTIONS.md');

/**
 * Aider adapter — export.js
 *
 * Aider uses two complementary files:
 *   1. `.aider.conf.yml`   — config file that points Aider to conventions
 *   2. `CONVENTIONS.md`    — flat Markdown with all skills compiled in
 *
 * The config tells Aider to load CONVENTIONS.md via `read:` directive and
 * pre-loads it as a read-only context file on every session.
 *
 * Format spec: https://aider.chat/docs/config/aider_conf.html
 */

function buildSkillSection(skillDir) {
  const skillName  = path.basename(skillDir);
  const skillMdPath  = path.join(skillDir, 'SKILL.md');
  const yamlPath   = path.join(skillDir, 'skill.yaml');

  let title = skillName;
  let description = '';
  if (fs.existsSync(yamlPath)) {
    const yaml = fs.readFileSync(yamlPath, 'utf8');
    title = extractYamlField(yaml, 'name') || skillName;
    description = extractYamlField(yaml, 'description') || '';
  }

  if (!fs.existsSync(skillMdPath)) return null;

  const raw = fs.readFileSync(skillMdPath, 'utf8');
  const body = stripFrontmatter(raw);

  if (!description) {
    const firstLine = body.split(/\r?\n/).map(l => l.trim()).find(l => l && !l.startsWith('#'));
    description = firstLine || '';
  }

  const descLine = description ? `> ${description.replace(/\r?\n+/g, ' ').trim()}\n` : '';
  const skillRef = `*Source: \`.agents/skills/${skillName}/SKILL.md\` — Load via \`/read .agents/skills/${skillName}/SKILL.md\`*\n`;
  return `\n## Skill: ${title}\n${descLine}${skillRef}`;
}

function generateAiderConf() {
  const conf = `# .aider.conf.yml
# Auto-generated by: node .agents/ctx.js export aider
# Source: .agents/core/skills/  ·  Do not edit manually.

# Load project conventions as a read-only context file on every session
read:
  - CONVENTIONS.md

# Recommended model settings (override as needed)
# model: gpt-4o
# editor-model: gpt-4o-mini

# Auto-commit after every accepted change
auto-commits: true

# Show diffs in git format
pretty: true
`;
  return conf;
}

function run() {
  console.log('Starting Aider adapter export...');

  // ── 1. Write .aider.conf.yml ─────────────────────────────────────────────────
  fs.writeFileSync(CONF_FILE, generateAiderConf());
  console.log(`Generated .aider.conf.yml → ${CONF_FILE}`);

  // ── 2. Build CONVENTIONS.md ──────────────────────────────────────────────────
  const sections = [];

  sections.push(
    `# CONVENTIONS.md — ContextOS Project Conventions\n\n` +
    `> Auto-generated by: node .agents/ctx.js export aider\n` +
    `> Source: .agents/core/skills/  ·  Do not edit manually.\n\n` +
    `Aider loads this file as read-only context on every session.\n` +
    `To keep your context window lean, load specific skill files on-demand using \`/read <path>\`.\n`
  );

  // Project rules with Step 0
  sections.push(
    `\n---\n\n## Project Rules\n\n` +
    `### Step 0 — Identify Before Acting\n\n` +
    `Before writing a single line of code or plan, state:\n` +
    `\`\`\`\n1. WHAT DOMAIN?   → Frontend / Backend / Architecture / Full-Stack / DevOps\n2. WHAT PHASE?    → Define / Plan / Build / Verify / Review / Ship\n3. WHAT ROLE?     → Declare specialist role for this phase\n\`\`\`\n` +
    `> **Anti-Spam Invariant**: Declare this strictly once at the start of a task or phase. Never repeat before intermediate tool calls or step updates.\n\n` +
    `### Non-Negotiable Rules\n\n` +
    `- **Zero-Assumption Investigation**: Never guess file paths or signatures. Inspect before modifying.\n` +
    `- **Zero-Placeholder Production Code**: Never emit lazy stubs, \`// TODO\`, or partial code.\n` +
    `- **Mandatory Proof-of-Work Verification**: Always run tests and validators before claiming completion.\n` +
    `- **Surgical Blast Radius**: Modify only files strictly within scope.\n` +
    `- **Fast-Track Exception**: Routine maintenance, git commands, version bumps, typo fixes, and diagnostics skip spec/plan ceremonies.\n`
  );

  // Skills Router Table
  sections.push('\n---\n\n## Skill Router\n\n');
  sections.push('Read the corresponding skill file only when the task matches the trigger:\n\n');
  sections.push('| Trigger / Domain | Skill | On-Demand Command |\n');
  sections.push('| --- | --- | --- |\n');

  const skills = collectSkillDirectories();
  for (const skill of skills) {
    const skillName = path.basename(skill);
    const yamlPath = path.join(skill, 'skill.yaml');
    let tags = skillName;
    if (fs.existsSync(yamlPath)) {
      const yaml = fs.readFileSync(yamlPath, 'utf8');
      const rawTags = extractYamlField(yaml, 'tags');
      if (rawTags) tags = rawTags.replace(/[\[\]]/g, '');
    }
    sections.push(`| \`${tags}\` | **${skillName}** | \`/read .agents/core/skills/${skillName}/SKILL.md\` |\n`);
  }

  // Skills
  sections.push('\n---\n\n# Skills\n');
  let count = 0;
  for (const skill of skills) {
    const section = buildSkillSection(skill);
    if (section) {
      sections.push(section);
      count++;
    }
  }

  fs.writeFileSync(CONVENTIONS_FILE, sections.join('\n'));
  console.log(`Generated CONVENTIONS.md (${count} skills) → ${CONVENTIONS_FILE}`);
}

module.exports = { run };
