/**
 * tests/adapter-safety.test.js
 * Unit tests for Task 1.3: Adapter Cleanup Safety (Cursor, Zed)
 */

const { test, describe, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { createLockfileData, recordManagedFile, saveLockfile } = require('../bin/lib/lockfile.js');

describe('Task 1.3: Adapter Cleanup Safety (Cursor, Zed)', () => {
  let tmpDir;
  const originalCwd = process.cwd();

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'contextos-adapter-test-'));
    process.chdir(tmpDir);

    // Setup minimal .agents/ structure
    fs.mkdirSync(path.join(tmpDir, '.agents', 'core', 'skills', 'react'), { recursive: true });
    fs.writeFileSync(
      path.join(tmpDir, '.agents', 'core', 'skills', 'react', 'SKILL.md'),
      '---\nname: react\ndescription: React skill\n---\n# React\nReact guidelines\n'
    );
    fs.writeFileSync(
      path.join(tmpDir, '.agents', 'AGENTS.md'),
      '# Project Rules\n'
    );
  });

  afterEach(() => {
    process.chdir(originalCwd);
    try {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    } catch {}
  });

  test('Cursor export preserves custom user .mdc files and cleans up only managed stale rules', () => {
    const cursorRulesDir = path.join(tmpDir, '.cursor', 'rules');
    fs.mkdirSync(cursorRulesDir, { recursive: true });

    // 1. User created rule
    const userRulePath = path.join(cursorRulesDir, 'my-custom-team-rule.mdc');
    fs.writeFileSync(userRulePath, '---\ndescription: "My team rule"\nglobs: "*"\n---\n# Custom Rule\n');

    // 2. Stale rule from previously managed skill
    const staleRuleRel = '.cursor/rules/stale-skill.mdc';
    const staleRulePath = path.join(tmpDir, staleRuleRel);
    const staleContent = '---\ndescription: "ContextOS rules for stale-skill"\n---\n<!-- Auto-generated by: node .agents/ctx.js export cursor -->\n# Stale\n';
    fs.writeFileSync(staleRulePath, staleContent);

    // Record stale in lockfile as managed
    const lock = createLockfileData();
    recordManagedFile(lock, staleRuleRel, staleContent);
    saveLockfile(tmpDir, lock);

    // Run cursor export
    const cursorAdapter = require('../.agents/adapters/cursor/export.js');
    cursorAdapter.run();

    // User rule MUST be preserved
    assert.ok(fs.existsSync(userRulePath), 'Custom user rule must not be deleted');
    assert.equal(fs.readFileSync(userRulePath, 'utf8').includes('My team rule'), true);

    // Stale managed rule must be cleaned up
    assert.equal(fs.existsSync(staleRulePath), false, 'Stale managed rule should be cleaned up');

    // Active skill rule must be present
    assert.ok(fs.existsSync(path.join(cursorRulesDir, 'react.mdc')), 'Active skill rule must be generated');
  });

  test('Zed export preserves custom user .md prompts and cleans up only managed stale prompts', () => {
    const zedPromptsDir = path.join(tmpDir, '.zed', 'prompts');
    fs.mkdirSync(zedPromptsDir, { recursive: true });

    // 1. User created prompt
    const userPromptPath = path.join(zedPromptsDir, 'my-custom-flow.md');
    fs.writeFileSync(userPromptPath, '# My Custom Prompt\nDo special user work\n');

    // 2. Stale prompt from previously managed skill
    const stalePromptRel = '.zed/prompts/stale-skill.md';
    const stalePromptPath = path.join(tmpDir, stalePromptRel);
    const staleContent = '<!-- Auto-generated by: node .agents/ctx.js export zed -->\n# ContextOS — stale-skill\n';
    fs.writeFileSync(stalePromptPath, staleContent);

    const lock = createLockfileData();
    recordManagedFile(lock, stalePromptRel, staleContent);
    saveLockfile(tmpDir, lock);

    // Run zed export
    const zedAdapter = require('../.agents/adapters/zed/export.js');
    zedAdapter.run();

    // User prompt MUST be preserved
    assert.ok(fs.existsSync(userPromptPath), 'Custom user prompt must not be deleted');
    assert.equal(fs.readFileSync(userPromptPath, 'utf8').includes('My Custom Prompt'), true);

    // Stale managed prompt must be cleaned up
    assert.equal(fs.existsSync(stalePromptPath), false, 'Stale managed prompt should be cleaned up');

    // Active skill prompt must be present
    assert.ok(fs.existsSync(path.join(zedPromptsDir, 'react.md')), 'Active skill prompt must be generated');
  });
});
