const fs = require('fs');
const path = require('path');
const { AGENTS_MD_PATH, collectSkillDirectories, extractYamlField, stripFrontmatter, readMeaningfulMarkdown } = require('../shared.js');

// Output paths
const OUTPUT_FILE = path.join(process.cwd(), '.cursorrules');
const CURSOR_RULES_DIR = path.join(process.cwd(), '.cursor', 'rules');

/**
 * Cursor adapter — export.js
 *
 * Generates:
 *   1. Modern modular Cursor rules in `.cursor/rules/<skill>.mdc` with glob filters
 *   2. Flat `.cursorrules` at project root for backwards compatibility
 *
 * Format spec: https://docs.cursor.com/context/rules-for-ai
 */

function getSkillGlobsAndFlags(skillName) {
  const ALWAYS_APPLY_SKILLS = ['engineering-workflow', 'gstack-roles', 'ponytail-mindset'];
  if (ALWAYS_APPLY_SKILLS.includes(skillName)) {
    return { globs: '', alwaysApply: true };
  }

  const FRONTEND_SKILLS = [
    'react', 'nextjs', 'typescript', 'ui-ux-pro', 'impeccable-design',
    'ui-design', 'ux-design', 'web-accessibility', 'brutalist-design',
    'minimalist-design', 'soft-design', 'redesign-audit', 'react-best-practices',
  ];
  if (FRONTEND_SKILLS.includes(skillName)) {
    return { globs: '**/*.{ts,tsx,js,jsx,css,scss,html}', alwaysApply: false };
  }

  const BACKEND_SKILLS = ['system-design', 'node', 'nestjs', 'microservices', 'ddd'];
  if (BACKEND_SKILLS.includes(skillName)) {
    return { globs: '**/*.{ts,js,json,prisma,sql}', alwaysApply: false };
  }

  if (skillName === 'database') {
    return { globs: '**/*.{prisma,sql,sqlite,db,drizzle.config.*}', alwaysApply: false };
  }

  if (skillName === 'docker') {
    return { globs: '**/Dockerfile*,**/docker-compose*.{yml,yaml}', alwaysApply: false };
  }

  if (skillName === 'testing') {
    return { globs: '**/*.{test,spec}.{ts,js,tsx,jsx},vitest.config.*,jest.config.*', alwaysApply: false };
  }

  if (skillName === 'state-management') {
    return { globs: '**/*{store,state,slice,reducer,atom}*.{ts,js,tsx,jsx}', alwaysApply: false };
  }

  if (skillName === 'performance' || skillName === 'vercel-optimize') {
    return { globs: '**/*.{ts,tsx,js,jsx,json}', alwaysApply: false };
  }

  if (skillName === 'fastapi') {
    return { globs: '**/*.{py,requirements.txt,Pipfile,pyproject.toml}', alwaysApply: false };
  }

  return { globs: '', alwaysApply: false };
}

function buildSkillSection(skillDir) {
  const skillName  = path.basename(skillDir);
  const skillMdPath  = path.join(skillDir, 'SKILL.md');
  const yamlPath   = path.join(skillDir, 'skill.yaml');

  let title = skillName;
  let description = '';
  if (fs.existsSync(yamlPath)) {
    const yaml = fs.readFileSync(yamlPath, 'utf8');
    title = extractYamlField(yaml, 'name') || skillName;
    description = extractYamlField(yaml, 'description') || '';
  }

  if (!fs.existsSync(skillMdPath)) {
    return null;
  }

  const raw = fs.readFileSync(skillMdPath, 'utf8');
  const body = stripFrontmatter(raw);

  if (!description) {
    const firstLine = body.split(/\r?\n/).map(l => l.trim()).find(l => l && !l.startsWith('#'));
    description = firstLine || '';
  }

  const descLine = description ? `> ${description.replace(/\r?\n+/g, ' ').trim()}\n` : '';
  return `\n## Skill: ${title}\n${descLine}*Rule file: \`.cursor/rules/${skillName}.mdc\` (load on demand)*\n`;
}

function generateCursorMdc(skillDir) {
  const skillName = path.basename(skillDir);
  const skillMdPath = path.join(skillDir, 'SKILL.md');
  const yamlPath = path.join(skillDir, 'skill.yaml');

  if (!fs.existsSync(skillMdPath)) return null;

  let title = skillName;
  let description = `ContextOS rules for ${skillName}`;
  if (fs.existsSync(yamlPath)) {
    const yaml = fs.readFileSync(yamlPath, 'utf8');
    title = extractYamlField(yaml, 'name') || skillName;
    const desc = extractYamlField(yaml, 'description');
    if (desc) description = desc;
  }

  let raw = fs.readFileSync(skillMdPath, 'utf8');
  const examples = readMeaningfulMarkdown(path.join(skillDir, 'EXAMPLES.md'));
  if (examples) raw += '\n\n' + examples;

  const troubleshooting = readMeaningfulMarkdown(path.join(skillDir, 'TROUBLESHOOTING.md'));
  if (troubleshooting) raw += '\n\n' + troubleshooting;

  const body = stripFrontmatter(raw);
  const { globs, alwaysApply } = getSkillGlobsAndFlags(skillName);

  const cleanDescription = description.replace(/\r?\n+/g, ' ').replace(/"/g, "'").trim();
  const mdcContent = `---
description: "${cleanDescription}"
globs: ${globs ? `"${globs}"` : '""'}
alwaysApply: ${alwaysApply}
---

# Skill: ${title}

${body}
`;

  return { skillName, mdcContent };
}

function run() {
  console.log('Starting Cursor adapter export...');

  const sections = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  sections.push(
    `# ContextOS — AI Rules for Cursor\n` +
    `# Auto-generated by: node .agents/ctx.js export cursor\n` +
    `# Source: .agents/core/skills/  ·  Do not edit manually.\n\n` +
    `> **Core law: Do not read everything. Read only what the current task requires.**\n\n` +
    `Detailed rules are modularized in \`.cursor/rules/*.mdc\` with file-glob activation.\n` +
    `Core orchestration is handled by \`.cursor/rules/00-project-rules.mdc\`.\n`
  );

  // Prepare .cursor/rules directory
  fs.mkdirSync(CURSOR_RULES_DIR, { recursive: true });

  let count = 0;
  let mdcCount = 0;

  // Write 00-project-rules.mdc
  if (fs.existsSync(AGENTS_MD_PATH)) {
    const agentsMd = fs.readFileSync(AGENTS_MD_PATH, 'utf8');
    const projectMdc = `---
description: "ContextOS core project rules and role orchestration"
globs: ""
alwaysApply: true
---

# ContextOS — Project Operating System Rules

${agentsMd}
`;
    fs.writeFileSync(path.join(CURSOR_RULES_DIR, '00-project-rules.mdc'), projectMdc);
    mdcCount++;
  }

  // ── Skills Index ─────────────────────────────────────────────────────────────
  sections.push('\n---\n\n# Skills Index (Loaded On-Demand)\n\n' +
    'The following specialist skills are configured as `.cursor/rules/<skill>.mdc`:\n');
  const skills = collectSkillDirectories();

  for (const skill of skills) {
    const section = buildSkillSection(skill);
    if (section) {
      sections.push(section);
      count++;
    }

    const mdc = generateCursorMdc(skill);
    if (mdc) {
      fs.writeFileSync(path.join(CURSOR_RULES_DIR, `${mdc.skillName}.mdc`), mdc.mdcContent);
      mdcCount++;
    }
  }

  fs.writeFileSync(OUTPUT_FILE, sections.join('\n'));
  console.log(`Generated .cursorrules (${count} skills) → ${OUTPUT_FILE}`);
  console.log(`Generated .cursor/rules/*.mdc (${mdcCount} rules) → ${CURSOR_RULES_DIR}`);
}

module.exports = { run };
