#!/usr/bin/env node
/**
 * merge-signals.mjs
 * Merges Vercel telemetry production metrics with codebase route scan outputs.
 *
 * Usage:
 *   node scripts/merge-signals.mjs <signals-file> <codebase-file> [--out <file>] [--help]
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

function printHelp() {
  console.log(`
merge-signals.mjs — Correlates Telemetry Metrics with Codebase Routes

Usage:
  node scripts/merge-signals.mjs <signals-file> <codebase-file> [options]

Arguments:
  signals-file           JSON file generated by collect-signals.mjs
  codebase-file          JSON file generated by scan-codebase.mjs

Options:
  --out <file>           Output destination file (default: stdout)
  --help, -h             Show this help message
`);
}

const args = process.argv.slice(2);
if (args.includes('--help') || args.includes('-h') || args.length < 2) {
  printHelp();
  process.exit(args.includes('--help') || args.includes('-h') ? 0 : 1);
}

const positional = [];
let outFile = null;

for (let i = 0; i < args.length; i++) {
  const arg = args[i];
  if (arg === '--out' && i + 1 < args.length) {
    outFile = args[++i];
  } else if (!arg.startsWith('-')) {
    positional.push(arg);
  }
}

if (positional.length < 2) {
  console.error('Error: Both <signals-file> and <codebase-file> are required.');
  process.exit(1);
}

const [signalsPath, codebasePath] = positional;
if (!existsSync(signalsPath)) {
  console.error(`Error: File not found: ${signalsPath}`);
  process.exit(1);
}
if (!existsSync(codebasePath)) {
  console.error(`Error: File not found: ${codebasePath}`);
  process.exit(1);
}

let signalsData = {};
let codebaseData = {};

try {
  signalsData = JSON.parse(readFileSync(resolve(process.cwd(), signalsPath), 'utf8'));
} catch (e) {
  console.error(`Error parsing signals JSON: ${e.message}`);
  process.exit(1);
}

try {
  codebaseData = JSON.parse(readFileSync(resolve(process.cwd(), codebasePath), 'utf8'));
} catch (e) {
  console.error(`Error parsing codebase JSON: ${e.message}`);
  process.exit(1);
}

const telemetryRoutes = signalsData.routes || [];
const codeRoutes = codebaseData.routes || [];

// Correlate metrics with source files
const mergedRoutes = [];

for (const tr of telemetryRoutes) {
  // Find matching route in codebase
  const match = codeRoutes.find(cr => {
    return cr.route === tr.route || cr.route === tr.route + '/' || tr.route === cr.route + '/';
  });

  mergedRoutes.push({
    ...tr,
    file: match ? match.file : null,
    frameworkConfig: match ? {
      type: match.type,
      dynamic: match.dynamic,
      revalidate: match.revalidate,
      runtime: match.runtime
    } : null
  });
}

// Add codebase routes that had no telemetry records
for (const cr of codeRoutes) {
  const existing = mergedRoutes.some(mr => mr.file === cr.file || mr.route === cr.route);
  if (!existing) {
    mergedRoutes.push({
      route: cr.route,
      method: 'GET',
      invocations: 0,
      p95DurationMs: 0,
      avgDurationMs: 0,
      coldStartRate: 0,
      errorRate: 0,
      cacheable: cr.dynamic === 'force-static' || cr.revalidate != null,
      file: cr.file,
      frameworkConfig: {
        type: cr.type,
        dynamic: cr.dynamic,
        revalidate: cr.revalidate,
        runtime: cr.runtime
      }
    });
  }
}

const merged = {
  timestamp: new Date().toISOString(),
  projectId: signalsData.projectId || 'unknown',
  windowDays: signalsData.windowDays || 14,
  framework: codebaseData.framework || 'unknown',
  metrics: signalsData.metrics || {},
  middleware: codebaseData.middleware || [],
  routes: mergedRoutes
};

const outputJson = JSON.stringify(merged, null, 2);
if (outFile) {
  writeFileSync(resolve(process.cwd(), outFile), outputJson, 'utf8');
} else {
  console.log(outputJson);
}
