/**
 * PR creation and issue commenting for the swarm GitHub Action.
 *
 * Uses the `gh` CLI (pre-installed on GitHub Actions runners) for all
 * GitHub API interactions. This is simpler and more reliable than Octokit
 * for the operations we need.
 */

import { execFileSync } from "node:child_process";

// ── Types ──────────────────────────────────────────────────────────────────

export interface SwarmJsonOutput {
	success: boolean;
	elapsed_s: number;
	iterations: number;
	sub_queries: number;
	threads: {
		total: number;
		completed: number;
		failed: number;
		cancelled: number;
	};
	budget: {
		spent_usd: number;
		limit_usd: number;
		actual_cost_threads: number;
		estimated_cost_threads: number;
	};
	tokens?: {
		input: number;
		output: number;
		total: number;
	};
	answer: string;
}

export interface PrResult {
	created: boolean;
	url?: string;
	error?: string;
}

export interface CommentResult {
	posted: boolean;
	error?: string;
}

// ── Helpers ────────────────────────────────────────────────────────────────

function gh(args: string[], options?: { input?: string }): string {
	try {
		const result = execFileSync("gh", args, {
			encoding: "utf-8",
			maxBuffer: 10 * 1024 * 1024,
			env: { ...process.env },
			input: options?.input,
		});
		return result.trim();
	} catch (err) {
		const msg = err instanceof Error ? err.message : String(err);
		throw new Error(`gh CLI failed: ${msg}`);
	}
}

function hasChanges(): boolean {
	try {
		const status = execFileSync("git", ["status", "--porcelain"], {
			encoding: "utf-8",
		}).trim();
		return status.length > 0;
	} catch {
		return false;
	}
}

function gitExec(args: string[]): string {
	return execFileSync("git", args, { encoding: "utf-8" }).trim();
}

// ── Branch + PR ────────────────────────────────────────────────────────────

/**
 * Create a branch with all current changes, push it, and open a PR.
 */
export function createPullRequest(
	task: string,
	output: SwarmJsonOutput,
	issueNumber?: number,
): PrResult {
	if (!hasChanges()) {
		return { created: false, error: "No file changes to commit" };
	}

	// Generate branch name from task
	const slug = task
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-|-$/g, "")
		.slice(0, 40) || "task";
	const branchName = `swarm/${slug}-${Date.now().toString(36)}`;

	try {
		// Create and switch to new branch
		gitExec(["checkout", "-b", branchName]);

		// Stage and commit all changes
		gitExec(["add", "-A"]);
		gitExec([
			"commit",
			"-m",
			`swarm: ${task.slice(0, 72)}`,
			"-m",
			buildCommitBody(output),
		]);

		// Push
		gitExec(["push", "origin", branchName]);

		// Create PR
		const prBody = buildPrBody(task, output, issueNumber);
		const prTitle = `swarm: ${task.length > 65 ? task.slice(0, 62) + "..." : task}`;

		const prUrl = gh([
			"pr", "create",
			"--title", prTitle,
			"--body", prBody,
			"--head", branchName,
		]);

		return { created: true, url: prUrl };
	} catch (err) {
		const msg = err instanceof Error ? err.message : String(err);
		return { created: false, error: msg };
	}
}

// ── Issue commenting ───────────────────────────────────────────────────────

/**
 * Post a comment on the originating issue with results.
 */
export function postIssueComment(
	issueNumber: number,
	task: string,
	output: SwarmJsonOutput,
	prResult?: PrResult,
): CommentResult {
	const body = buildIssueComment(task, output, prResult);

	try {
		gh(["issue", "comment", String(issueNumber), "--body", body]);
		return { posted: true };
	} catch (err) {
		const msg = err instanceof Error ? err.message : String(err);
		return { posted: false, error: msg };
	}
}

/**
 * Post a failure comment when swarm encounters an error.
 */
export function postFailureComment(
	issueNumber: number,
	task: string,
	error: string,
): CommentResult {
	const body = [
		`### Swarm Failed`,
		"",
		`**Task:** ${task}`,
		"",
		`**Error:**`,
		"```",
		error.slice(0, 1000),
		"```",
		"",
		"---",
		`*Generated by [swarm-code](https://github.com/kingjulio8238/swarm-code)*`,
	].join("\n");

	try {
		gh(["issue", "comment", String(issueNumber), "--body", body]);
		return { posted: true };
	} catch (err) {
		const msg = err instanceof Error ? err.message : String(err);
		return { posted: false, error: msg };
	}
}

// ── Body builders ──────────────────────────────────────────────────────────

function buildCommitBody(output: SwarmJsonOutput): string {
	const lines: string[] = [];
	lines.push(`Threads: ${output.threads.completed} completed, ${output.threads.failed} failed`);
	lines.push(`Cost: $${output.budget.spent_usd.toFixed(4)}`);
	lines.push(`Duration: ${output.elapsed_s.toFixed(1)}s`);
	lines.push("");
	lines.push("Generated by swarm-code");
	return lines.join("\n");
}

function buildPrBody(
	task: string,
	output: SwarmJsonOutput,
	issueNumber?: number,
): string {
	const lines: string[] = [];

	lines.push("## Summary");
	lines.push("");
	lines.push(`**Task:** ${task}`);
	if (issueNumber) {
		lines.push(`**Issue:** #${issueNumber}`);
	}
	lines.push("");

	// Answer
	if (output.answer) {
		lines.push("### What was done");
		lines.push("");
		lines.push(output.answer);
		lines.push("");
	}

	// Stats
	lines.push("### Stats");
	lines.push("");
	lines.push(`| Metric | Value |`);
	lines.push(`|--------|-------|`);
	lines.push(`| Status | ${output.success ? "Completed" : "Incomplete"} |`);
	lines.push(`| Threads | ${output.threads.completed} completed, ${output.threads.failed} failed |`);
	lines.push(`| Cost | $${output.budget.spent_usd.toFixed(4)} |`);
	lines.push(`| Duration | ${output.elapsed_s.toFixed(1)}s |`);
	lines.push(`| Iterations | ${output.iterations} |`);
	if (output.tokens) {
		const totalK = (output.tokens.total / 1000).toFixed(1);
		lines.push(`| Tokens | ${totalK}K (${output.tokens.input.toLocaleString()} in + ${output.tokens.output.toLocaleString()} out) |`);
	}
	lines.push("");

	if (issueNumber) {
		lines.push(`Closes #${issueNumber}`);
		lines.push("");
	}

	lines.push("---");
	lines.push("*Generated by [swarm-code](https://github.com/kingjulio8238/swarm-code)*");

	return lines.join("\n");
}

function buildIssueComment(
	task: string,
	output: SwarmJsonOutput,
	prResult?: PrResult,
): string {
	const lines: string[] = [];

	const icon = output.success ? "white_check_mark" : "warning";
	lines.push(`### :${icon}: Swarm ${output.success ? "Completed" : "Finished (incomplete)"}`);
	lines.push("");

	if (prResult?.created && prResult.url) {
		lines.push(`**PR:** ${prResult.url}`);
		lines.push("");
	} else if (prResult && !prResult.created) {
		if (prResult.error === "No file changes to commit") {
			lines.push("> No file changes were made. The answer is below.");
		} else {
			lines.push(`> Could not create PR: ${prResult.error}`);
		}
		lines.push("");
	}

	// Brief answer
	if (output.answer) {
		const answerPreview = output.answer.length > 500
			? output.answer.slice(0, 497) + "..."
			: output.answer;
		lines.push("<details>");
		lines.push("<summary>Answer</summary>");
		lines.push("");
		lines.push(answerPreview);
		lines.push("");
		lines.push("</details>");
		lines.push("");
	}

	// Stats
	lines.push(`**Threads:** ${output.threads.completed} completed, ${output.threads.failed} failed`);
	lines.push(`**Cost:** $${output.budget.spent_usd.toFixed(4)} · **Duration:** ${output.elapsed_s.toFixed(1)}s`);

	lines.push("");
	lines.push("---");
	lines.push("*Generated by [swarm-code](https://github.com/kingjulio8238/swarm-code)*");

	return lines.join("\n");
}
