/**
 * Mock agent backend — for integration testing without real API keys.
 *
 * Simulates a coding agent by writing actual files in the work directory.
 * Registered as "mock" and "mock-reviewer" in the agent registry.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import type { AgentProvider, AgentResult, AgentRunOptions } from "../core/types.js";
import { registerAgent } from "./provider.js";

const mockProvider: AgentProvider = {
	name: "mock",

	async isAvailable(): Promise<boolean> {
		return true;
	},

	async run(options: AgentRunOptions): Promise<AgentResult> {
		const { task, workDir, signal } = options;
		const startTime = Date.now();

		// Check for abort
		if (signal?.aborted) {
			return {
				success: false,
				output: "Aborted",
				filesChanged: [],
				diff: "",
				durationMs: Date.now() - startTime,
				error: "Aborted before start",
			};
		}

		// Simulate work delay (20ms)
		await new Promise((resolve) => setTimeout(resolve, 20));

		// Check for forced failure mode
		if (task.includes("__FAIL__")) {
			return {
				success: false,
				output: "Simulated failure",
				filesChanged: [],
				diff: "",
				durationMs: Date.now() - startTime,
				error: "Mock agent forced failure",
			};
		}

		// Handle review evaluation tasks cleanly if invoked as reviewer
		if (task.includes("Independent Code Reviewer") || task.includes("specCompliance") || task.includes("codeQuality")) {
			if (task.includes("__MALFORMED__")) {
				return {
					success: true,
					output: "Unparseable non-json response",
					filesChanged: [],
					diff: "",
					durationMs: Date.now() - startTime,
				};
			}
			const specCompliance = task.includes("__FAIL_SPEC__") ? "FAIL" : "PASS";
			const codeQuality = task.includes("__FAIL_QUALITY__") ? "FAIL" : "PASS";
			return {
				success: true,
				output: JSON.stringify({
					specCompliance,
					codeQuality,
					summary: `Review completed: spec=${specCompliance}, quality=${codeQuality}`,
				}),
				filesChanged: [],
				diff: "",
				durationMs: Date.now() - startTime,
				usage: { inputTokens: 500, outputTokens: 200, totalTokens: 700 },
			};
		}

		// Write actual files in the work directory to simulate agent edits
		const filesChanged: string[] = [];

		// Create or modify a file based on the task
		const targetFile = path.join(workDir, "hello.ts");
		const content = `// Generated by mock agent\n// Task: ${task}\nexport function hello(): string {\n\treturn "Hello from swarm thread!";\n}\n`;
		fs.writeFileSync(targetFile, content, "utf-8");
		filesChanged.push("hello.ts");

		// If task mentions "multi", create additional files
		if (task.toLowerCase().includes("multi")) {
			const extraFile = path.join(workDir, "utils.ts");
			fs.writeFileSync(extraFile, '// Utility module\nexport const VERSION = "1.0.0";\n', "utf-8");
			filesChanged.push("utils.ts");
		}

		const output = [
			"Applied edit to hello.ts",
			`Created ${filesChanged.length} file(s)`,
			"Result: Successfully completed task",
		].join("\n");

		return {
			success: true,
			output,
			filesChanged,
			diff: "", // Diff is captured by worktree manager
			durationMs: Date.now() - startTime,
			// Simulate token usage for testing budget tracking
			usage: {
				inputTokens: 1500,
				outputTokens: 800,
				totalTokens: 2300,
			},
		};
	},
};

export const mockReviewerProvider: AgentProvider = {
	name: "mock-reviewer",

	async isAvailable(): Promise<boolean> {
		return true;
	},

	async run(options: AgentRunOptions): Promise<AgentResult> {
		const { task, signal } = options;
		const startTime = Date.now();

		if (signal?.aborted) {
			return {
				success: false,
				output: "Aborted",
				filesChanged: [],
				diff: "",
				durationMs: Date.now() - startTime,
				error: "Aborted before start",
			};
		}

		if (task.includes("__TIMEOUT__")) {
			await new Promise((resolve) => setTimeout(resolve, 35000));
		}

		if (task.includes("__MALFORMED__")) {
			return {
				success: true,
				output: "This is completely unparseable non-JSON text from the reviewer.",
				filesChanged: [],
				diff: "",
				durationMs: Date.now() - startTime,
			};
		}

		if (task.includes("__ERROR__") || task.includes("__FAIL__")) {
			return {
				success: false,
				output: "",
				filesChanged: [],
				diff: "",
				durationMs: Date.now() - startTime,
				error: "Independent reviewer model execution failed",
			};
		}

		const specCompliance = task.includes("__FAIL_SPEC__") ? "FAIL" : "PASS";
		const codeQuality = task.includes("__FAIL_QUALITY__") ? "FAIL" : "PASS";

		return {
			success: true,
			output: JSON.stringify({
				specCompliance,
				codeQuality,
				summary:
					specCompliance === "PASS" && codeQuality === "PASS"
						? "Independent code review passed"
						: `Independent code review verdict: spec=${specCompliance}, quality=${codeQuality}`,
			}),
			filesChanged: [],
			diff: "",
			durationMs: Date.now() - startTime,
			usage: {
				inputTokens: 600,
				outputTokens: 250,
				totalTokens: 850,
			},
		};
	},
};

registerAgent(mockProvider);
registerAgent(mockReviewerProvider);
registerAgent({
	...mockReviewerProvider,
	name: "reviewer-independent",
});

export default mockProvider;
