const fs = require('fs');
const path = require('path');
const { AGENTS_MD_PATH, collectSkillDirectories, extractYamlField, stripFrontmatter, readMeaningfulMarkdown } = require('../shared.js');

// Output destinations for Zed
const ZED_DIR = path.join(process.cwd(), '.zed');
const RULES_FILE = path.join(ZED_DIR, 'rules.md');
const PROMPTS_DIR = path.join(ZED_DIR, 'prompts');

/**
 * Zed IDE adapter — export.js
 *
 * Generates:
 *   1. `.zed/rules.md` — Project assistant instructions loaded into Zed's context
 *   2. `.zed/prompts/*.md` — Modular slash-command prompts for Zed Assistant
 *
 * Format spec: https://zed.dev/docs/assistant
 */

function buildSkillSection(skillDir) {
  const skillName  = path.basename(skillDir);
  const skillMdPath  = path.join(skillDir, 'SKILL.md');
  const yamlPath   = path.join(skillDir, 'skill.yaml');

  let title = skillName;
  let description = '';
  if (fs.existsSync(yamlPath)) {
    const yaml = fs.readFileSync(yamlPath, 'utf8');
    title = extractYamlField(yaml, 'name') || skillName;
    description = extractYamlField(yaml, 'description') || '';
  }

  if (!fs.existsSync(skillMdPath)) return null;

  const raw = fs.readFileSync(skillMdPath, 'utf8');
  const body = stripFrontmatter(raw);

  if (!description) {
    const firstLine = body.split(/\r?\n/).map(l => l.trim()).find(l => l && !l.startsWith('#'));
    description = firstLine || '';
  }

  const descLine = description ? `> ${description.replace(/\r?\n+/g, ' ').trim()}\n` : '';
  const promptRef = `*Prompt template: \`.zed/prompts/${skillName}.md\` (Use via /${skillName})*\n`;
  return {
    skillName,
    title,
    section: `\n### Skill: ${title}\n${descLine}${promptRef}`,
    prompt: `<!-- Auto-generated by: node .agents/ctx.js export zed -->\n# ContextOS — ${title}\n\n${descLine}\n${body}\n`,
  };
}

function run() {
  console.log('Starting Zed IDE adapter export...');

  const zedDir = path.join(process.cwd(), '.zed');
  const rulesFile = path.join(zedDir, 'rules.md');
  const promptsDir = path.join(zedDir, 'prompts');
  const agentsMdPath = fs.existsSync(path.join(process.cwd(), '.agents', 'AGENTS.md'))
    ? path.join(process.cwd(), '.agents', 'AGENTS.md')
    : AGENTS_MD_PATH;

  fs.mkdirSync(zedDir, { recursive: true });
  fs.mkdirSync(promptsDir, { recursive: true });

  const lines = [];

  // ── Header ───────────────────────────────────────────────────────────────────
  lines.push(
    `# ContextOS — AI Rules for Zed Assistant\n`,
    `<!-- Auto-generated by: node .agents/ctx.js export zed -->\n`,
    `<!-- Source: .agents/core/skills/  ·  Do not edit manually. -->\n\n`
  );

  // ── Project Rules ────────────────────────────────────────────────────────────
  if (fs.existsSync(agentsMdPath)) {
    const agentsMd = fs.readFileSync(agentsMdPath, 'utf8');
    lines.push(`## Project Rules (AGENTS.md)\n\n${agentsMd}\n\n---\n`);

    // Also write a master prompt in .zed/prompts/contextos.md
    fs.writeFileSync(
      path.join(promptsDir, 'contextos.md'),
      `<!-- Auto-generated by: node .agents/ctx.js export zed -->\n# ContextOS Master Prompt\n\n${agentsMd}\n`
    );
  }

  // ── Skills ───────────────────────────────────────────────────────────────────
  lines.push(`\n## Skills Library\n`);
  lines.push(`The following specialist skills guide architecture and implementation:\n`);

  const skills = collectSkillDirectories();
  const activePromptFiles = new Set(['contextos.md']);
  let count = 0;

  for (const skill of skills) {
    const skillData = buildSkillSection(skill);
    if (skillData) {
      lines.push(skillData.section);
      const promptFileName = `${skillData.skillName}.md`;
      activePromptFiles.add(promptFileName);
      fs.writeFileSync(path.join(promptsDir, promptFileName), skillData.prompt);
      count++;
    }
  }

  // Clean up stale prompts from uninstalled skills/plugins safely (provenance-verified only)
  if (fs.existsSync(promptsDir)) {
    const lockfilePath = path.join(process.cwd(), '.agents', 'contextos.lock.json');
    let lockData = null;
    try {
      if (fs.existsSync(lockfilePath)) {
        lockData = JSON.parse(fs.readFileSync(lockfilePath, 'utf8'));
      }
    } catch {}

    for (const file of fs.readdirSync(promptsDir)) {
      if (file.endsWith('.md') && !activePromptFiles.has(file)) {
        const fullFilePath = path.join(promptsDir, file);
        const relPath = path.relative(process.cwd(), fullFilePath).replace(/\\/g, '/');

        const isManagedInLock = Boolean(lockData?.managedFiles?.[relPath]?.managed);
        let hasContextosMarker = false;
        try {
          const content = fs.readFileSync(fullFilePath, 'utf8');
          hasContextosMarker =
            content.includes('<!-- Auto-generated by: node .agents/ctx.js export zed -->') ||
            content.includes('# ContextOS —') ||
            content.includes('# ContextOS Master Prompt');
        } catch {}

        if (isManagedInLock || hasContextosMarker) {
          fs.unlinkSync(fullFilePath);
          if (lockData?.managedFiles?.[relPath]) {
            delete lockData.managedFiles[relPath];
            try {
              fs.writeFileSync(lockfilePath, JSON.stringify(lockData, null, 2) + '\n', 'utf8');
            } catch {}
          }
        }
      }
    }
  }

  // Write master .zed/rules.md
  fs.writeFileSync(rulesFile, lines.join(''));
  console.log(`Generated .zed/rules.md (${count} skills) → ${rulesFile}`);
  console.log(`Generated .zed/prompts/*.md (${count} prompts) → ${promptsDir}`);
}

module.exports = { run };
