const fs = require('fs');
const path = require('path');
const { AGENTS_MD_PATH, collectSkillDirectories, extractYamlField, stripFrontmatter, readMeaningfulMarkdown } = require('../shared.js');

// GitHub Copilot reads from .github/copilot-instructions.md
const OUTPUT_FILE = path.join(process.cwd(), '.github', 'copilot-instructions.md');

/**
 * GitHub Copilot adapter — export.js
 *
 * Copilot reads `.github/copilot-instructions.md` as a plain Markdown file.
 * We compile AGENTS.md + all skills into one document with clear section
 * headings so Copilot can reference them contextually.
 *
 * Format spec: https://docs.github.com/en/copilot/customizing-copilot/adding-repository-instructions
 */

function buildSkillSection(skillDir) {
  const skillName  = path.basename(skillDir);
  const skillMdPath  = path.join(skillDir, 'SKILL.md');
  const yamlPath   = path.join(skillDir, 'skill.yaml');

  let title = skillName;
  let description = '';
  if (fs.existsSync(yamlPath)) {
    const yaml = fs.readFileSync(yamlPath, 'utf8');
    title = extractYamlField(yaml, 'name') || skillName;
    description = extractYamlField(yaml, 'description') || '';
  }

  if (!fs.existsSync(skillMdPath)) return null;

  const raw = fs.readFileSync(skillMdPath, 'utf8');
  const body = stripFrontmatter(raw);

  if (!description) {
    const firstLine = body.split(/\r?\n/).map(l => l.trim()).find(l => l && !l.startsWith('#'));
    description = firstLine || '';
  }

  const descLine = description ? `> ${description.replace(/\r?\n+/g, ' ').trim()}\n` : '';
  const skillRef = `*Source: \`.agents/skills/${skillName}/SKILL.md\` (Read on demand)*\n`;
  return `\n### ${title}\n${descLine}${skillRef}`;
}

function run() {
  console.log('Starting GitHub Copilot adapter export...');

  const lines = [];

  // ── Header ───────────────────────────────────────────────────────────────────
  lines.push(
    `# GitHub Copilot Instructions — ContextOS\n`,
    `<!-- Auto-generated by: node .agents/ctx.js export copilot -->\n`,
    `<!-- Source: .agents/core/skills/  ·  Do not edit manually. -->\n\n`
  );

  // ── Project rules & Step 0 ───────────────────────────────────────────────────
  lines.push(`## Project Rules\n\n`);
  lines.push(`### Step 0 — Identify Before Acting\n\n`);
  lines.push(`Before writing a single line of code or plan, state:\n`);
  lines.push(`\`\`\`\n1. WHAT DOMAIN?   → Frontend / Backend / Architecture / Full-Stack / DevOps\n2. WHAT PHASE?    → Define / Plan / Build / Verify / Review / Ship\n3. WHAT ROLE?     → Declare specialist role for this phase\n\`\`\`\n\n`);
  lines.push(`### Non-Negotiable Rules\n\n`);
  lines.push(`- **Zero-Assumption Investigation**: Never guess file paths or signatures. Inspect before modifying.\n`);
  lines.push(`- **Zero-Placeholder Production Code**: Never emit lazy stubs, \`// TODO\`, or partial code.\n`);
  lines.push(`- **Mandatory Proof-of-Work Verification**: Always run tests and validators before claiming completion.\n`);
  lines.push(`- **Surgical Blast Radius**: Modify only files strictly within scope.\n\n`);
  lines.push(`---\n`);

  // ── Skills ───────────────────────────────────────────────────────────────────
  lines.push(`\n## Skills Library\n\n`);
  lines.push(`ContextOS uses on-demand progressive disclosure. Read the relevant \`SKILL.md\` file only when your task matches the trigger.\n\n`);
  lines.push(`### Skill Routing Table\n\n`);
  lines.push(`| Trigger / Domain | Skill | Path |\n`);
  lines.push(`| --- | --- | --- |\n`);

  const skills = collectSkillDirectories();
  for (const skill of skills) {
    const skillName = path.basename(skill);
    const yamlPath = path.join(skill, 'skill.yaml');
    let tags = skillName;
    if (fs.existsSync(yamlPath)) {
      const yaml = fs.readFileSync(yamlPath, 'utf8');
      const rawTags = extractYamlField(yaml, 'tags');
      if (rawTags) tags = rawTags.replace(/[\[\]]/g, '');
    }
    const relPath = `.agents/core/skills/${skillName}/SKILL.md`;
    lines.push(`| \`${tags}\` | **${skillName}** | \`${relPath}\` |\n`);
  }
  lines.push(`\n---\n`);

  let count = 0;
  for (const skill of skills) {
    const section = buildSkillSection(skill);
    if (section) {
      lines.push(section);
      count++;
    }
  }

  // ── Write ────────────────────────────────────────────────────────────────────
  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, lines.join(''));
  console.log(`Generated .github/copilot-instructions.md (${count} skills) → ${OUTPUT_FILE}`);
}

module.exports = { run };
